# Generated by Django 4.0.6 on 2022-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Inserted')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('code', models.CharField(help_text='The app is selecting a parser according to this code.', max_length=40, verbose_name='Code')),
                ('homepage_link', models.URLField(verbose_name='Homepage link')),
                ('starting_source_link', models.URLField(help_text='Parser starts scanning the marketplace at this link and expecting pagination.', verbose_name='Starting source link')),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
            },
        ),
    ]
