# Generated by Django 4.0.6 on 2022-07-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Inserted')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('homepage_link', models.URLField(verbose_name='Homepage link')),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
            },
        ),
    ]
