# Generated by Django 4.0.6 on 2022-07-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Inserted')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('size', models.CharField(choices=[('1+kk', '1+kk'), ('1+1', '1+1'), ('2+kk', '2+kk'), ('2+1', '2+1'), ('3+kk', '3+kk'), ('3+1', '3+1'), ('4+', '4 and more')], max_length=10, verbose_name='Size')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
