# Generated by Django 4.0.6 on 2022-08-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Inserted')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('start_scanning_date', models.DateTimeField(verbose_name='Start scanning date')),
                ('end_scanning_date', models.DateTimeField(blank=True, null=True, verbose_name='End scanning date')),
                ('properties_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.marketplace', verbose_name='Marketplace')),
            ],
            options={
                'verbose_name': 'Marketplace Data',
                'verbose_name_plural': 'Marketplaces data',
            },
        ),
    ]
