# Generated by Django 4.0.6 on 2022-07-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001__'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='code',
            field=models.CharField(default=1, help_text='The app is selecting a parser according to this code.', max_length=40, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
