version: '2.4'

services:

  app:
    container_name: real-estate-hunter-app
    hostname: real-estate-hunter-app
    image: flakooo/myprojects:real-estate-hunter-app
    restart: always
    depends_on:
      - db
    volumes:
      - "..:/opt/real-estate-hunter"
    environment:
      DB_HOST: "real-estate-hunter-db"
      DB_PORT: "3306"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_PASSWORD: "1122"
      DJANGO_SUPERUSER_EMAIL: "test@gmail.com"
    ports:
      - "8088:8088"

  db:
    container_name: real-estate-hunter-db
    hostname: real-estate-hunter-db
    image: flakooo/myprojects:real-estate-hunter-db
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"

volumes:
  db_data: